spring:
  kafka:
    bootstrap-servers: localhost:29092
  liquibase:
    enabled: true
    change-log: classpath:db/master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/Final-task
    username: postgres
    password: pass

  mail:
    host: smtp.gmail.com
    port: 587
    username: a92387400@gmail.com
    password: zzldzhlaxdfbxbzv #Alesha`123
    templates:
      path: mail-templates
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  messages:
    basename: mailMessages
    encoding: UTF-8
jwt:
  header: Authorization
  secret: 2F413F442A472D4B6150645367566B59703373367639792442264529482B4D62
  expiration: 60
logging:
  file:
    name: log/myapp.log
auth:
  adminCode: Admin