create table public.users
(
    id          bigint generated by default as identity
        primary key,
    ban         boolean,
    description varchar(255),
    email       varchar(255)
        constraint users_email_uindex
            unique,
    first_name  varchar(255),
    last_name   varchar(255),
    password    varchar(255),
    phone       varchar(255),
    rating      real,
    role        varchar(255)
);

alter table public.users
    owner to postgres;

create table public.adverts
(
    id          bigint generated by default as identity
        constraint advert_pkey
            primary key,
    date        timestamp(6),
    description varchar(255),
    premium     boolean,
    price       integer,
    title       varchar(255),
    user_id     bigint
        constraint adverts_users_id_fk
            references public.users,
    ban         boolean
);

alter table public.adverts
    owner to postgres;

create table public.comments
(
    id        bigint generated always as identity
        constraint comment_pk
            primary key,
    advert_id integer                  not null
        constraint comments_adverts_id_fk
            references public.adverts,
    user_id   integer                  not null
        constraint comments_users_id_fk
            references public.users,
    date      timestamp with time zone not null,
    text      text                     not null,
    ban       boolean
);

alter table public.comments
    owner to postgres;

create table public.votes
(
    author_id integer                  not null
        constraint vote_users_id_fk
            references public.users,
    date      timestamp with time zone not null,
    vote      integer                  not null,
    advert_id bigint                   not null
        constraint vote_advert_id_fk
            references public.adverts,
    constraint vote_pk
        primary key (author_id, advert_id)
);

alter table public.votes
    owner to postgres;

create table public.chats
(
    id        bigint generated always as identity
        constraint chat_pk
            primary key,
    advert_id integer not null
        constraint chats_adverts_id_fk
            references public.adverts,
    buyer_id  integer not null
        constraint chats_users_id_fk
            references public.users
);

alter table public.chats
    owner to postgres;

create unique index chat_id_uindex
    on public.chats (id);

create table public.messages
(
    chat_id integer                  not null
        constraint message_chat_null_fk
            references public.chats,
    text    text                     not null,
    date    timestamp with time zone not null,
    id      bigint generated always as identity
        constraint message_pkey
            primary key
        constraint message_id_key
            unique
);

alter table public.messages
    owner to postgres;

